###  Representações Vetoriais para Palavras, Sentenças e Documentos

In [ ]:
import numpy as np

vetor1 = np.array([1., 2., 1., 4.])
vetor2 = np.zeros(4)
vetor3 = np.ones(4)

print('Vetor 1:', vetor1)
print('Vetor 2:', vetor2)
print('Vetor 3:', vetor3)

Vetor 1: [1. 2. 1. 4.]
Vetor 2: [0. 0. 0. 0.]
Vetor 3: [1. 1. 1. 1.]


In [ ]:
[1,2] * 2

[1, 2, 1, 2]

In [ ]:
vetor1 * 2

array([2., 4., 2., 8.])

In [ ]:
vetor1 + vetor3

array([2., 3., 2., 5.])

In [ ]:
vetor1 - vetor3

array([0., 1., 0., 3.])

In [ ]:
vetor1 * vetor3 # termo a termo

array([1., 2., 1., 4.])

In [ ]:
np.dot(vetor1, vetor3) # produto escalar

np.float64(8.0)

In [ ]:
vetor1 @ vetor3 # produto escalar

np.float64(8.0)

In [ ]:
vetor3 / vetor1 # termo a termo

array([1.  , 0.5 , 1.  , 0.25])

### Similaridade Cosseno

<img src="https://miro.medium.com/v2/resize:fit:720/format:webp/1*LfW66-WsYkFqWc4XYJbEJg.png" alt="Similaridade Cosseno" width="300">

In [ ]:
from numpy.linalg import norm

A = np.array([1, 2, 3])
B = np.array([3, 2, 1])

A @ B / ( norm(A) * norm(B) )

np.float64(0.7142857142857143)

In [ ]:
A = np.array([1, 2, 3])
B = np.array([1, 2.1, 3])

A @ B / ( norm(A) * norm(B) )

np.float64(0.9997521255198267)

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_similarity([A], [B])

array([[0.99975213]])

## Modelo de vetorização de palavras (Embeddings)

In [ ]:
!pip install safetensors

In [ ]:
#https://huggingface.co/nilc-nlp/word2vec-skip-gram-50d/tree/main

from safetensors.torch import load_file
tensors = load_file("embeddings.safetensors")
vectors = tensors["embeddings"]  # torch.Tensor

In [ ]:
!wget https://huggingface.co/nilc-nlp/word2vec-skip-gram-50d/resolve/main/embeddings.safetensors

--2025-11-02 12:41:27--  https://huggingface.co/nilc-nlp/word2vec-skip-gram-50d/resolve/main/embeddings.safetensors
Resolving huggingface.co (huggingface.co)... 3.170.185.14, 3.170.185.25, 3.170.185.35, ...
Connecting to huggingface.co (huggingface.co)|3.170.185.14|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://cas-bridge.xethub.hf.co/xet-bridge-us/68cf218919e94baa06c86deb/153575e60ed68acdecdfbd42cf137ec21f508dfcfeea07d22cfa63216d466216?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=cas%2F20251102%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20251102T124127Z&X-Amz-Expires=3600&X-Amz-Signature=a24eefeb3369ec847675aa76bb58708e637c691f6bccd1d051601fa6fd78ff2c&X-Amz-SignedHeaders=host&X-Xet-Cas-Uid=public&response-content-disposition=inline%3B+filename*%3DUTF-8%27%27embeddings.safetensors%3B+filename%3D%22embeddings.safetensors%22%3B&x-id=GetObject&Expires=1762090887&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6ey

In [ ]:
vectors.shape

torch.Size([929606, 50])

In [ ]:
from gensim.models import KeyedVectors
word2vec = KeyedVectors.load_word2vec_format('cbow_s50.txt')

In [ ]:
!pip install gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 96.9 MB/s eta 0:00:00


In [ ]:
import gensim.downloader
# Show all available models in gensim-data
print(list(gensim.downloader.info()['models'].keys()))

['fasttext-wiki-news-subwords-300', 'conceptnet-numberbatch-17-06-300', 'word2vec-ruscorpora-300', 'word2vec-google-news-300', 'glove-wiki-gigaword-50', 'glove-wiki-gigaword-100', 'glove-wiki-gigaword-200', 'glove-wiki-gigaword-300', 'glove-twitter-25', 'glove-twitter-50', 'glove-twitter-100', 'glove-twitter-200', '__testing_word2vec-matrix-synopsis']


In [ ]:
gensim.downloader.load('glove-twitter-50')
word2vec = gensim.downloader.load('glove-twitter-50')
word2vec['computer']  # numpy vector of a word

[==================================================] 100.0% 199.5/199.5MB downloaded


array([ 0.65572  ,  0.50502  , -0.64935  ,  0.14142  , -0.73858  ,
       -0.060631 ,  0.5229   , -1.4541   ,  0.79533  , -0.05805  ,
        0.6463   ,  0.57013  , -3.7753   , -0.2414   , -0.16999  ,
       -0.57056  ,  0.45857  ,  0.53634  , -0.45337  , -0.13149  ,
       -0.94989  ,  0.063493 ,  0.47575  ,  0.34153  , -1.2699   ,
       -0.0061569, -0.47168  , -0.68425  , -0.31045  ,  0.5198   ,
       -0.3573   , -0.97569  , -0.37267  , -1.3218   ,  0.27268  ,
       -0.72485  ,  0.46634  ,  0.40591  ,  0.17259  , -0.61372  ,
       -0.39455  ,  1.406    , -1.3402   ,  0.21337  ,  0.30572  ,
       -0.043278 , -0.019297 ,  0.62462  , -0.78825  ,  0.29806  ],
      dtype=float32)

In [ ]:
#gensim.downloader.load('word2vec-google-news-300')
#word2vec = gensim.downloader.load('word2vec-google-news-300')
#word2vec['computer']  # numpy vector of a word

In [ ]:
cosine_similarity([word2vec['men']], [word2vec['boy']])

array([[0.6701945]], dtype=float32)

In [ ]:
cosine_similarity([word2vec['boy']], [word2vec['girl']])

array([[0.9283967]], dtype=float32)

In [ ]:
cosine_similarity([word2vec['boy']], [word2vec['chair']])

array([[0.45625213]], dtype=float32)

In [ ]:
word2vec.most_similar('computer', topn=5)

[('cell', 0.8157469630241394),
 ('laptop', 0.811658501625061),
 ('desktop', 0.8046691417694092),
 ('phone', 0.8026933670043945),
 ('computers', 0.7978081703186035)]

In [ ]:
word2vec.most_similar(positive=['king', 'woman'], negative=['man'], topn=1)

[('prince', 0.759779691696167)]

### Modelo mais avançado de Embeddings

In [ ]:
!pip install transformers

In [ ]:
import torch
from transformers import AutoTokenizer, AutoModel

device = 'cpu'

tokenizer = AutoTokenizer.from_pretrained('neuralmind/bert-large-portuguese-cased', do_lower_case=False)
bert = AutoModel.from_pretrained('neuralmind/bert-large-portuguese-cased')
bert = bert.to(device)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/155 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/648 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.34G [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.34G [00:00<?, ?B/s]

In [ ]:
texto = 'Eu vou ao banco pagar a conta hoje.'

# tokenizando o texto
input_ids = tokenizer.encode(texto, return_tensors='pt')
wordpieces = tokenizer.convert_ids_to_tokens(input_ids[0])

# salvando ponteiros para palavras
subwords_idx = [] # first subword of each word
for i, wordpiece in enumerate(wordpieces):
    if '##' not in wordpiece and i not in [0, len(wordpieces)-1]:
        subwords_idx.append(i)

# obtendo os vetores para as palavras
input_ids = input_ids.to(device)
with torch.no_grad():
  outs = bert(input_ids)
  vetores1 = outs[0][0, :]

vetores1[subwords_idx]

tensor([[ 0.7381,  0.6351,  0.4160,  ..., -0.5735, -0.9812, -0.6793],
        [ 0.6583, -0.0975,  0.2579,  ..., -0.7367, -0.8734,  0.1407],
        [ 0.7682,  0.2151,  0.1769,  ...,  1.0626, -0.2526, -0.3107],
        ...,
        [-0.0765,  0.4402, -0.5236,  ...,  0.8389, -0.3389, -0.8167],
        [ 0.3460,  1.8568, -0.0262,  ..., -0.0021, -0.0928,  0.0079],
        [ 0.8516,  1.1038, -1.1464,  ...,  0.4630, -0.4967,  0.2980]])

In [ ]:
texto2 = 'Vou sentar no banco da praça.'

# tokenizando o texto
input_ids = tokenizer.encode(texto2, return_tensors='pt')
wordpieces = tokenizer.convert_ids_to_tokens(input_ids[0])

# salvando ponteiros para palavras
subwords_idx = [] # first subword of each word
for i, wordpiece in enumerate(wordpieces):
    if '##' not in wordpiece and i not in [0, len(wordpieces)-1]:
        subwords_idx.append(i)

# obtendo os vetores para as palavras
input_ids = input_ids.to(device)
with torch.no_grad():
  outs = bert(input_ids)
  vetores2 = outs[0][0, :]

vetores2[subwords_idx]

tensor([[ 0.6666,  0.7042,  0.4914,  ..., -0.7679, -0.9684, -0.2469],
        [ 0.3655,  0.6842,  0.5443,  ..., -0.4190, -0.2330, -0.0836],
        [ 0.4563, -0.1144, -0.0323,  ...,  0.3872,  0.0522,  0.1594],
        ...,
        [ 0.5797,  0.1973, -0.0097,  ..., -0.0610,  0.0090, -0.1254],
        [-0.0989, -0.1823, -0.1768,  ...,  0.1509, -0.6715,  0.1678],
        [ 0.6592,  0.6043, -0.5467,  ..., -0.0842, -0.1656,  0.0563]])

## Exemplo

In [ ]:
import pandas as pd

df = pd.read_csv('Tweets_Mg.csv')
df

Unnamed: 0                      Created At  \
0              0  Sun Jan 08 01:22:05 +0000 2017   
1              1  Sun Jan 08 01:49:01 +0000 2017   
2              2  Sun Jan 08 01:01:46 +0000 2017   
3              3  Wed Jan 04 21:43:51 +0000 2017   
4              4  Mon Jan 09 15:08:21 +0000 2017   
...          ...                             ...   
8194        8194  Thu Feb 09 11:48:07 +0000 2017   
8195        8195  Thu Feb 09 12:10:19 +0000 2017   
8196        8196  Thu Feb 09 12:04:17 +0000 2017   
8197        8197  Thu Feb 09 12:10:04 +0000 2017   
8198        8198  Tue Feb 07 15:01:30 +0000 2017   

                                                   Text  \
0     ���⛪ @ Catedral de Santo Antônio - Governador ...   
1     � @ Governador Valadares, Minas Gerais https:/...   
2     �� @ Governador Valadares, Minas Gerais https:...   
3                           ��� https://t.co/BnDsO34qK0   
4     ��� PSOL vai questionar aumento de vereadores ...   
...                                                 ...   
8194  Trio é preso suspeito de roubo, tráfico e abus...   
8195  Trio é preso suspeito de roubo, tráfico e abus...   
8196  Trio é preso suspeito de roubo, tráfico e abus...   
8197  Trio é preso suspeito de roubo, tráfico e abus...   
8198  Trio suspeito de roubo de cargas é preso em Sa...   

      Geo Coordinates.latitude  Geo Coordinates.longitude  \
0                          NaN                        NaN   
1                     -41.9333                     -18.85   
2                     -41.9333                     -18.85   
3                          NaN                        NaN   
4                          NaN                        NaN   
...                        ...                        ...   
8194                       NaN                        NaN   
8195                       NaN                        NaN   
8196                       NaN                        NaN   
8197                       NaN                        NaN   
8198                       NaN                        NaN   

                      User Location              Username User Screen Name  \
0                            Brasil  Leonardo C Schneider    LeoCSchneider   
1                               NaN               Wândell         klefnews   
2                               NaN               Wândell         klefnews   
3                               NaN         Ana estudando  estudandoconcur   
4                               NaN                 Emily         Milly777   
...                             ...                   ...              ...   
8194                            NaN             Ana Lúcia  lapiseirapentel   
8195  Belo Horizonte - Minas Gerais       Marcelo Rezende         Televans   
8196                 Guarulhos - SP   Leonardo Nascimento      leonardogru   
8197                Brasil Natal/RN    Lucas Medeiros �©™  parabolicalucas   
8198            Belo Horizonte - MG        RecordTV Minas    tvrecordminas   

      Retweet Count Classificacao  ... Unnamed: 15  Unnamed: 16  Unnamed: 17  \
0                 0        Neutro  ...         NaN          NaN          NaN   
1                 0        Neutro  ...         NaN          NaN          NaN   
2                 0        Neutro  ...         NaN          NaN          NaN   
3                 0        Neutro  ...         NaN          NaN          NaN   
4                 0      Negativo  ...         NaN          NaN          NaN   
...             ...           ...  ...         ...          ...          ...   
8194              0      Positivo  ...         NaN          NaN          NaN   
8195              0      Positivo  ...         NaN          NaN          NaN   
8196              0      Positivo  ...         NaN          NaN          NaN   
8197              0      Positivo  ...         NaN          NaN          NaN   
8198              0      Positivo  ...         NaN          NaN          NaN   

      Unnamed: 18  Unnamed: 19  Unnamed: 

In [ ]:
df.columns

Index(['Unnamed: 0', 'Created At', 'Text', 'Geo Coordinates.latitude',
       'Geo Coordinates.longitude', 'User Location', 'Username',
       'User Screen Name', 'Retweet Count', 'Classificacao', 'Observação',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24'],
      dtype='object')

In [ ]:
df['Classificacao'].value_counts()

Classificacao
Positivo    3300
Neutro      2453
Negativo    2446
Name: count, dtype: int64

In [ ]:
df['Text']

0       ���⛪ @ Catedral de Santo Antônio - Governador ...
1       � @ Governador Valadares, Minas Gerais https:/...
2       �� @ Governador Valadares, Minas Gerais https:...
3                             ��� https://t.co/BnDsO34qK0
4       ��� PSOL vai questionar aumento de vereadores ...
                              ...                        
8194    Trio é preso suspeito de roubo, tráfico e abus...
8195    Trio é preso suspeito de roubo, tráfico e abus...
8196    Trio é preso suspeito de roubo, tráfico e abus...
8197    Trio é preso suspeito de roubo, tráfico e abus...
8198    Trio suspeito de roubo de cargas é preso em Sa...
Name: Text, Length: 8199, dtype: object

In [ ]:
import nltk
nltk.download('stopwords')
stopwords = nltk.corpus.stopwords.words('portuguese')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(stop_words=stopwords)

vetores = vectorizer.fit_transform(df['Text'])
vocab = vectorizer.get_feature_names_out()



In [ ]:
pd.DataFrame(vetores.toarray(), columns=vocab).head(5).to_excel('encoding.xlsx')

In [ ]:
X = vetores
y, label = pd.factorize(df['Classificacao'])

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

# Criando e treinando o classificador
clf = MultinomialNB()
clf.fit(X_train, y_train)

MultinomialNB()

In [ ]:
y_pred = clf.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Acurácia:", accuracy)

Acurácia: 0.9567073170731707


## Persistindo o modelo

In [ ]:
import pickle

with open('model.pkl', 'wb') as f:
    pickle.dump(clf, f)

Como carregar?


In [ ]:
model_persistido = pickle.load(open('model.pkl', 'rb'))

In [ ]:
y_pred2 = model_persistido.predict(X_test)

accuracy = accuracy_score(y_test, y_pred2)
print("Acurácia:", accuracy)

Acurácia: 0.9567073170731707


*Testando nosso modelo em uma nova entrada:*

In [ ]:
novo_texto = input("Digite um texto: ")
novo_texto_vetorizado = vectorizer.transform([novo_texto])
previsao = clf.predict(novo_texto_vetorizado)
label[previsao[0]]

In [ ]:
df[df['Classificacao'] == 'Negativo']['Text']

In [ ]:
df[df['Classificacao'] == 'Positivo']['Text']

65      #DefesaAgropecuária "Governo de Minas Gerais a...
66      #EBC Governo de Minas investiga casos suspeito...
87      #Minas vai dobrar oferta de trabalho e estudo ...
88      #Minas vai dobrar oferta de trabalho e estudo ...
108     #SUS Minas Gerais recebe recurso máximo dispon...
                              ...                        
8194    Trio é preso suspeito de roubo, tráfico e abus...
8195    Trio é preso suspeito de roubo, tráfico e abus...
8196    Trio é preso suspeito de roubo, tráfico e abus...
8197    Trio é preso suspeito de roubo, tráfico e abus...
8198    Trio suspeito de roubo de cargas é preso em Sa...
Name: Text, Length: 3300, dtype: object

---